server:
  port: 9094

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create
      show-sql: 'true'
  datasource:
    testWhileIdle: 'true'
    validationQuery: SELECT 1
    platform: postgres
  cloud:
    loadbalancer:
      ribbon:
        enabled: 'false'
  database:
    driverClassName: org.postgresql.Driver

eureka:
  instance:
    preferIpAddress: 'true'
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: 'true'