eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: http://localhost:9092/eureka/

management:
  endpoints:
    web:
      exposure:
        include: *
    enabled-by-default: true

