spring:
  application:
    name: licensing-service
  cloud:
    config:
      uri: http://localhost:9091
  config:
    import: "optional:configserver:"
logging:
  level:
    org.springframework.web: WARN
    com.optimagrowth: DEBUG