server:
  port: 9090
management:
  endpoint:
    health:
      show-components: always
      show-details: always
spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://configserver:9091
