server:
  port: 9999
spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:9091
  config:
    import: "optional:configserver:"
management:
  endpoints:
    web:
      exposure:
        include: "*"

