spring:
  application:
    name: licensing-service
  main:
    allow-circular-references: true
gateway:
  port: 9095

logging:
  level:
    org.springframework.web: WARN
    com.optimagrowth: DEBUG

redis:
  port: 6379
  host: redis
