example:
  property: DEV
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://database:5432/ostock_dev
    password: '0520'

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:9092/eureka/