example:
  property: PROD
spring:
  datasource:
    url: jdbc:postgresql://database:5432/ostock_prod
    username: postgres
    password: 0520

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:9999/eureka/