example:
  property: DEV
spring:
  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: orgChangeTopic
          group: licensingGroup
          content-type: application/json
      kafka:
        binder:
          zkNodes: kafka1
          brokers: kafka1:9092
  datasource:
    username: postgres
    url: jdbc:postgresql://database:5432/ostock_dev
    password: '0520'

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:9999/eureka/

redis:
  server: redisserver