example:
  property: LOCAL
spring:
  datasource:
    username: postgres
    password: '0520'
    url: jdbc:postgresql://localhost:5432/ostock_local
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: localhost:19092
          brokers: localhost:19092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/