spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:9091
    loadbalancer:
      ribbon:
        enabled: false
  config:
    import: "optional:configserver:"











