example:
  property: LOCAL
spring:
  datasource:
    username: postgres
    password: '0520'
    url: jdbc:postgresql://localhost:5432/ostock_local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9092/eureka/